let effect1 = {
  type: "damage",
  val: 20,
  name: "Uzumaki Combo",
  description: "",
  id: "narutoskill1",
  caster: "naruto",
  turnid: "",
  target: "target",
  duration: 1,
  during: "this turn",
  after: [],
  condition: [],
  persistence: "instant",
  class: "physical",
  current: 0,
  usage: 0,
  stack: 0,
  charge: 0,
  multi: 0,
  active: true,
  isStack: false,
  isInvisible: false,
  isMulti: false,
  isUnremovable: false,
  isMarking: false,
  isHarmful: false,
  isPiercing: false,
  isActive: false,
  isLastTurn: false,
  isAllowed: true,
  isNoCounter: false
};

let skill1 = {
  name: "Uzumaki Combo",
  description: "",
  picture: "https://i.imgur.com/N7Icwsp.jpg",
  classes: "instant, physical",
  id: "",
  index: 0,
  caster: "naruto",
  persistence: "instant",
  class: "physical",
  effects: [effect1],
  target: "enemy",
  cooldown: 0,
  cost: {
    g: 1,
    b: 0,
    r: 0,
    w: 0,
    rd: 0
  },
  counter: 0,
  active: true,
  store: [],
  isHarmful: true,
  isAllowed: true,
  isCooldown: false,
  isStore: false,
  isNoCounter: false,
  isIgnoreStun: false,
  isIgnoreInvul: false
};

let effect2a = {
  type: "damage",
  val: 45,
  name: "",
  description: "",
  id: "",
  caster: "",
  turnid: "",
  target: "target",
  duration: 1,
  during: "this turn",
  after: [],
  condition: [],
  persistence: "instant",
  class: "mental",
  scope: ['none'],
  specify: ["skill name", "consideration"],
  current: 0,
  usage: 0,
  stack: 0,
  charge: 0,
  multi: 0,
  active: true,
  isStack: false,
  isInvisible: false,
  isMulti: false,
  isUnremovable: false,
  isMarking: false,
  isHarmful: false,
  isPiercing: false,
  isActive: false,
  isLastTurn: false,
  isAllowed: true,
  isNoCounter: false
};

let effect2b = {
  type: "stun",
  name: "",
  description: "",
  id: "",
  caster: "",
  turnid: "",
  target: "target",
  duration: 1,
  during: "next turn",
  after: [],
  condition: [],
  persistence: "",
  class: "mental",
  scope: ['none'],
  specify: ["skill name", "consideration"],
  current: 0,
  usage: 0,
  stack: 0,
  charge: 0,
  multi: 0,
  active: true,
  isStack: false,
  isInvisible: false,
  isMulti: false,
  isUnremovable: false,
  isMarking: false,
  isHarmful: false,
  isPiercing: false,
  isActive: false,
  isLastTurn: false,
  isAllowed: true,
  isNoCounter: false
};

let skill2 = {
  name: "Rasengan",
  description: "",
  picture: "https://i.imgur.com/K85sYdM.jpg",
  classes: "instant, energy",
  id: "narutoskill2",
  index: 1,
  caster: "naruto",
  persistence: "instant",
  class: "mental",
  effects: [effect2a, effect2b],
  target: "enemy",
  cooldown: 1,
  cost: {
    g: 0,
    b: 1,
    r: 0,
    w: 0,
    rd: 1
  },
  counter: 0,
  active: true,
  store: [],
  isHarmful: true,
  isAllowed: [
    { default: false },
    {
      subject: "allow", //What to look at
      evaluator: "exist", //How to evaluate
      comparison: "Shadow Clones", //Comparison against what. Can be an array with String and Number
      value: true //value to return after
    }
  ],
  isCooldown: false,
  isStore: false,
  isNoCounter: false,
  isIgnoreStun: false,
  isIgnoreInvul: false
};

let effect3a = {
  type: "allow",
  name: "Shadow Clones",
  description: "",
  id: "",
  caster: "",
  turnid: "",
  target: "target",
  duration: 4,
  during: "next turn",
  after: [],
  condition: [],
  persistence: "instant",
  class: "energy",
  scope: ['none'],
  specify: ["skill name", "consideration"],
  current: 0,
  usage: 0,
  stack: 0,
  charge: 0,
  multi: 0,
  active: true,
  isStack: false,
  isInvisible: false,
  isMulti: false,
  isUnremovable: false,
  isMarking: false,
  isHarmful: false,
  isPiercing: false,
  isActive: false,
  isLastTurn: false,
  isAllowed: true,
  isNoCounter: false
};

let effect3b = {
  type: "buff",
  val: 10,
  scope: ['skills', 'Shadow Clones'],
  name: "",
  description: "",
  id: "",
  caster: "",
  turnid: "",
  target: "target",
  duration: 4,
  during: "next turn",
  after: [],
  condition: [],
  persistence: "instant",
  class: "energy",
  current: 0,
  usage: 0,
  stack: 0,
  charge: 0,
  multi: 0,
  active: true,
  isStack: false,
  isInvisible: false,
  isMulti: false,
  isUnremovable: false,
  isMarking: false,
  isHarmful: false,
  isPiercing: false,
  isActive: false,
  isLastTurn: false,
  isAllowed: true,
  isNoCounter: false
};

let effect3c = {
  type: "dr",
  val: 15,
  name: "",
  description: "",
  id: "",
  caster: "",
  turnid: "",
  target: "target",
  duration: 4,
  during: "next turn",
  after: [],
  condition: [],
  persistence: "instant",
  class: "energy",
  scope: ['none'],
  specify: ["skill name", "consideration"],
  current: 0,
  usage: 0,
  stack: 0,
  charge: 0,
  multi: 0,
  active: true,
  isStack: false,
  isInvisible: false,
  isMulti: false,
  isUnremovable: false,
  isMarking: false,
  isHarmful: false,
  isPiercing: false,
  isActive: false,
  isLastTurn: false,
  isAllowed: true,
  isNoCounter: false
};

let skill3 = {
  name: "Shadow Clones",
  description: "",
  picture: "https://i.imgur.com/HgwONmv.jpg",
  classes: "",
  id: "",
  index: 2,
  caster: "",
  persistence: "instant",
  class: "energy",
  effects: [effect3a, effect3b, effect3c],
  target: "self",
  cooldown: 3,
  cost: {
    g: 0,
    b: 0,
    r: 0,
    w: 0,
    rd: 1
  },
  counter: 0,
  active: true,
  store: [],
  isHarmful: true,
  isAllowed: true,
  isCooldown: false,
  isStore: false,
  isNoCounter: false,
  isIgnoreStun: false,
  isIgnoreInvul: false
};

let effect4 = {
  type: "invul",
  name: "",
  description: "",
  id: "",
  caster: "",
  turnid: "",
  target: "target",
  duration: 1,
  during: "next turn",
  after: [],
  condition: [],
  persistence: "instant",
  class: "strategic",
  scope: ['none'],
  specify: ["skill name", "consideration"],
  current: 0,
  usage: 0,
  stack: 0,
  charge: 0,
  multi: 0,
  active: true,
  isStack: false,
  isInvisible: false,
  isMulti: false,
  isUnremovable: false,
  isMarking: false,
  isHarmful: false,
  isPiercing: false,
  isActive: false,
  isLastTurn: false,
  isAllowed: true,
  isNoCounter: false
};

let skill4 = {
  name: "Sexy Technique",
  description: "",
  picture: "https://i.imgur.com/SRh8P5d.jpg",
  classes: "",
  id: "",
  index: 3,
  caster: "",
  persistence: "instant",
  class: "strategic",
  effects: [effect4],
  target: "self",
  cooldown: 4,
  cost: {
    g: 0,
    b: 0,
    r: 0,
    w: 0,
    rd: 1
  },
  counter: 0,
  active: true,
  store: [],
  isHarmful: true,
  isAllowed: true,
  isCooldown: false,
  isStore: false,
  isNoCounter: false,
  isIgnoreStun: false,
  isIgnoreInvul: false
};

let char = {
  name: "naruto",
  description: "",
  picture: "https://i.imgur.com/cC0JLiQ.jpg",
  anime: "",
  credit: {
    author: "",
    pictures: "",
    coder: ""
  },
  maxHp: 100,
  category: [],
  id: "naruto",
  status: {
    onAttack: [],
    onReceive: [],
    onSkill: [],
    onState: []
  },
  skills: [skill1, skill2, skill3, skill4],
  hp: 100,
  alive: true
};

module.exports = char;

console.log("nothing's wrong");
